// flow-typed signature: a4841f3e54115d0b97105e316d1f829e
// flow-typed version: <<STUB>>/babel-plugin-transform-promise-to-bluebird_v^2.0.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-promise-to-bluebird'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-promise-to-bluebird' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-promise-to-bluebird/main.cjs' {
  declare module.exports: any;
}

declare module 'babel-plugin-transform-promise-to-bluebird/main.mjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-promise-to-bluebird/main.cjs.js' {
  declare module.exports: $Exports<'babel-plugin-transform-promise-to-bluebird/main.cjs'>;
}
declare module 'babel-plugin-transform-promise-to-bluebird/main.mjs.js' {
  declare module.exports: $Exports<'babel-plugin-transform-promise-to-bluebird/main.mjs'>;
}
