// flow-typed signature: c64db9b6f9a66b85505c8fd9c3602cd9
// flow-typed version: <<STUB>>/safe-access-check_v^0.0.15/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'safe-access-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'safe-access-check' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'safe-access-check/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'safe-access-check/lib/index' {
  declare module.exports: $Exports<'safe-access-check/lib'>;
}
declare module 'safe-access-check/lib/index.js' {
  declare module.exports: $Exports<'safe-access-check/lib'>;
}
