// flow-typed signature: 1b4054bd42ba8ab9346881b68a30a5aa
// flow-typed version: <<STUB>>/@babel/helper-plugin-utils_v^7.8.3/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/helper-plugin-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/helper-plugin-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/helper-plugin-utils/lib' {
  declare module.exports: any;
}

declare module '@babel/helper-plugin-utils/src' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/helper-plugin-utils/lib/index' {
  declare module.exports: $Exports<'@babel/helper-plugin-utils/lib'>;
}
declare module '@babel/helper-plugin-utils/lib/index.js' {
  declare module.exports: $Exports<'@babel/helper-plugin-utils/lib'>;
}
declare module '@babel/helper-plugin-utils/src/index' {
  declare module.exports: $Exports<'@babel/helper-plugin-utils/src'>;
}
declare module '@babel/helper-plugin-utils/src/index.js' {
  declare module.exports: $Exports<'@babel/helper-plugin-utils/src'>;
}
