// flow-typed signature: 040101dda9baa9ed1c858115a6d7ecfe
// flow-typed version: <<STUB>>/@babel/plugin-proposal-pipeline-operator_v^7.0.0/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-pipeline-operator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-pipeline-operator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-pipeline-operator/lib/buildOptimizedSequenceExpression' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/lib/fsharpVisitor' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/lib' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/lib/minimalVisitor' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-pipeline-operator/lib/smartVisitor' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-pipeline-operator/lib/buildOptimizedSequenceExpression.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib/buildOptimizedSequenceExpression'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/fsharpVisitor.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib/fsharpVisitor'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/minimalVisitor.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib/minimalVisitor'>;
}
declare module '@babel/plugin-proposal-pipeline-operator/lib/smartVisitor.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-pipeline-operator/lib/smartVisitor'>;
}
